In [1]:
import pandas as pd
import requests
import geopandas as gpd

# Gather Crop Yield(corn,soybean,wheat) History for Tennessee from 2000 to 2024.

In [2]:
# create private API key
import json
with open('keys.json') as fi:
    credentials = json.load(fi)
usda_crop_api_key = credentials['usda_crop_api_key']
noaa_weather_api_key = credentials['noaa_weather_api_key']

In [3]:
# Base URL for USDA NASS Quick Stats API 
crop_base_url = 'https://quickstats.nass.usda.gov/api/api_GET/'

crop_records = []

field_crops = ['CORN','SOYBEANS', 'WHEAT']

for field_crop in field_crops:
    for year in range(2000, 2025):  # Excludes 2025
        
# Define Query Parameters for filtering the data set   
# Get the keys from https://quickstats.nass.usda.gov/api from 'usage page'
        
        params = {
            'key': usda_crop_api_key,
            'commodity_desc': field_crop,
            'year': str(year),
            'state_name': 'TENNESSEE',
            'statisticcat_desc': 'YIELD', 
            'unit_desc': 'BU / ACRE'
        }
        
      # Send Get Request to USDA API with Parameters
        crop_response = requests.get(crop_base_url, params=params)
      # Convert API Response in to Python dictonary
        crop_data = crop_response.json()
        #data.keys()   # get key dictionary
        if "data" in crop_data:
            crop_records.extend(crop_data["data"])

In [4]:
print(type(crop_records))
print(len(crop_records))

<class 'list'>
5384

In [5]:
#Convert crop yield from list to Data frame
crop_df = pd.DataFrame(crop_records)

In [6]:
# Export Raw Crop Data frame to csv file
crop_df.to_csv('../data/Raw_Crop_df', index=False)

In [7]:
crop_df.head()

,congr_district_code,statisticcat_desc,group_desc,prodn_practice_desc,watershed_code,source_desc,begin_code,country_code,Value,watershed_desc,...,county_ansi,freq_desc,util_practice_desc,sector_desc,state_ansi,county_name,state_alpha,location_desc,load_time,end_code
0,,YIELD,FIELD CROPS,ALL PRODUCTION PRACTICES,00000000,SURVEY,00,9000,131,,...,,ANNUAL,GRAIN,CROPS,47,,TN,"TENNESSEE, DELTA",2012-01-01 00:00:00.000,00
1,,YIELD,FIELD CROPS,ALL PRODUCTION PRACTICES,00000000,SURVEY,00,9000,109,,...,,ANNUAL,GRAIN,CROPS,47,,TN,"TENNESSEE, WEST TENNESSEE",2012-01-01 00:00:00.000,00
2,,YIELD,FIELD CROPS,ALL PRODUCTION PRACTICES,00000000,SURVEY,00,9000,106,,...,,ANNUAL,GRAIN,CROPS,47,,TN,"TENNESSEE, WESTERN RIM",2012-01-01 00:00:00.000,00
3,,YIELD,FIELD CROPS,ALL PRODUCTION PRACTICES,00000000,SURVEY,00,9000,102,,...,,ANNUAL,GRAIN,CROPS,47,,TN,"TENNESSEE, CENTRAL BASIN",2012-01-01 00:00:00.000,00
4,,YIELD,FIELD CROPS,ALL PRODUCTION PRACTICES,00000000,SURVEY,00,9000,125,,...,,ANNUAL,GRAIN,CROPS,47,,TN,"TENNESSEE, CUMBERLAND PLATEAU",2012-01-01 00:00:00.000,00

In [8]:
crop_df[['commodity_desc','year','state_name','statisticcat_desc','unit_desc','Value','county_name']]

,commodity_desc,year,state_name,statisticcat_desc,unit_desc,Value,county_name
0,CORN,2000,TENNESSEE,YIELD,BU / ACRE,131,
1,CORN,2000,TENNESSEE,YIELD,BU / ACRE,109,
2,CORN,2000,TENNESSEE,YIELD,BU / ACRE,106,
3,CORN,2000,TENNESSEE,YIELD,BU / ACRE,102,
4,CORN,2000,TENNESSEE,YIELD,BU / ACRE,125,
...,...,...,...,...,...,...,...
5379,WHEAT,2024,TENNESSEE,YIELD,BU / ACRE,75,
5380,WHEAT,2024,TENNESSEE,YIELD,BU / ACRE,76,
5381,WHEAT,2024,TENNESSEE,YIELD,BU / ACRE,76,
5382,WHEAT,2024,TENNESSEE,YIELD,BU / ACRE,76,
5383,WHEAT,2024,TENNESSEE,YIELD,BU / ACRE,80,

In [9]:
crop_df["county_name"].unique()

array(['', 'DYER', 'LAKE', 'LAUDERDALE', 'OBION', 'SHELBY', 'TIPTON',
       'BENTON', 'CARROLL', 'CHESTER', 'CROCKETT', 'DECATUR', 'FAYETTE',
       'GIBSON', 'HARDEMAN', 'HARDIN', 'HAYWOOD', 'HENDERSON', 'HENRY',
       'MCNAIRY', 'MADISON', 'WEAKLEY', 'OTHER (COMBINED) COUNTIES',
       'CHEATHAM', 'DICKSON', 'HICKMAN', 'HUMPHREYS', 'LAWRENCE',
       'MONTGOMERY', 'PERRY', 'ROBERTSON', 'STEWART', 'WAYNE', 'BEDFORD',
       'CANNON', 'DAVIDSON', 'DE KALB', 'GILES', 'LINCOLN', 'MACON',
       'MARSHALL', 'MAURY', 'MOORE', 'RUTHERFORD', 'SMITH', 'SUMNER',
       'TROUSDALE', 'WILLIAMSON', 'WILSON', 'BLEDSOE', 'COFFEE',
       'CUMBERLAND', 'FENTRESS', 'FRANKLIN', 'GRUNDY', 'MARION',
       'OVERTON', 'SEQUATCHIE', 'WARREN', 'WHITE', 'BLOUNT', 'BRADLEY',
       'COCKE', 'GREENE', 'HAMBLEN', 'JEFFERSON', 'MCMINN', 'MEIGS',
       'MONROE', 'POLK', 'RHEA', 'WASHINGTON', 'PUTNAM', 'CLAIBORNE',
       'GRAINGER', 'HAWKINS', 'JOHNSON', 'SULLIVAN', 'LOUDON', 'HAMILTON',
       'CARTER', 'CLAY', 'VAN BUREN', 'SEVIER', 'JACKSON', 'PICKETT',
       'KNOX', 'MORGAN', 'CAMPBELL', 'OTHER COUNTIES', 'LEWIS'],
      dtype=object)

In [11]:
crop_df[
    ~crop_df["county_name"].isin(
        ["OTHER COUNTIES", "OTHER (COMBINED) COUNTIES"]
    )
]

,congr_district_code,statisticcat_desc,group_desc,prodn_practice_desc,watershed_code,source_desc,begin_code,country_code,Value,watershed_desc,...,county_ansi,freq_desc,util_practice_desc,sector_desc,state_ansi,county_name,state_alpha,location_desc,load_time,end_code
0,,YIELD,FIELD CROPS,ALL PRODUCTION PRACTICES,00000000,SURVEY,00,9000,131,,...,,ANNUAL,GRAIN,CROPS,47,,TN,"TENNESSEE, DELTA",2012-01-01 00:00:00.000,00
1,,YIELD,FIELD CROPS,ALL PRODUCTION PRACTICES,00000000,SURVEY,00,9000,109,,...,,ANNUAL,GRAIN,CROPS,47,,TN,"TENNESSEE, WEST TENNESSEE",2012-01-01 00:00:00.000,00
2,,YIELD,FIELD CROPS,ALL PRODUCTION PRACTICES,00000000,SURVEY,00,9000,106,,...,,ANNUAL,GRAIN,CROPS,47,,TN,"TENNESSEE, WESTERN RIM",2012-01-01 00:00:00.000,00
3,,YIELD,FIELD CROPS,ALL PRODUCTION PRACTICES,00000000,SURVEY,00,9000,102,,...,,ANNUAL,GRAIN,CROPS,47,,TN,"TENNESSEE, CENTRAL BASIN",2012-01-01 00:00:00.000,00
4,,YIELD,FIELD CROPS,ALL PRODUCTION PRACTICES,00000000,SURVEY,00,9000,125,,...,,ANNUAL,GRAIN,CROPS,47,,TN,"TENNESSEE, CUMBERLAND PLATEAU",2012-01-01 00:00:00.000,00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5379,,YIELD,FIELD CROPS,ALL PRODUCTION PRACTICES,00000000,SURVEY,00,9000,75,,...,,ANNUAL,ALL UTILIZATION PRACTICES,CROPS,47,,TN,TENNESSEE,2025-09-30 12:00:00.000,00
5380,,YIELD,FIELD CROPS,ALL PRODUCTION PRACTICES,00000000,SURVEY,00,9000,76,,...,,ANNUAL,ALL UTILIZATION PRACTICES,CROPS,47,,TN,TENNESSEE,2024-08-12 12:00:00.000,00
5381,,YIELD,FIELD CROPS,ALL PRODUCTION PRACTICES,00000000,SURVEY,00,9000,76,,...,,ANNUAL,ALL UTILIZATION PRACTICES,CROPS,47,,TN,TENNESSEE,2024-07-12 12:00:00.000,00
5382,,YIELD,FIELD CROPS,ALL PRODUCTION PRACTICES,00000000,SURVEY,00,9000,76,,...,,ANNUAL,ALL UTILIZATION PRACTICES,CROPS,47,,TN,TENNESSEE,2024-06-12 12:00:00.000,00
5383,,YIELD,FIELD CROPS,ALL PRODUCTION PRACTICES,00000000,SURVEY,00,9000,80,,...,,ANNUAL,ALL UTILIZATION PRACTICES,CROPS,47,,TN,TENNESSEE,2024-05-10 12:00:00.000,00

In [13]:
crop_df.shape

(5384, 39)

# Gather weather History from 2000 to 2024

### Get all NOAA weather stations in Tennessee

In [14]:
# Weather observations are recorded at stations, not counties.
# We first need the station IDs and their latitude/longitude before downloading weather measurements.

In [15]:
# Call Stations end point to get stationsid to find the Counties after merging it weather data
stations_base_url = "https://www.ncei.noaa.gov/cdo-web/api/v2/stations"

# Authentication token
headers = {
    "token": noaa_weather_api_key
}

# Query Parameters to filter stations
params = {
    "datasetid": "GSOM",         # Monthly Summary Data
    "locationid": "FIPS:47",     # TN state Fips code 47
    "startdate": "2000-01-01",   # Start date filter for station availabilty
    "enddate": "2024-12-31",     # End date filter
    "limit": 1000,               # Max Records per one API Request
    "offset": 1                  # pagination start index
}

# List to store all station records
all_stations = []

# Loop to handle pagination
while True:

    # Make API request to NOAA stations endpoint
    response = requests.get(stations_base_url, headers=headers, params=params)

    # Stop if API call fails
    if response.status_code != 200:
        print("Request failed:", response.text)
        break

    # Convert JSON response to Python dictionary
    data = response.json()

    # Extract station records from response
    results = data.get("results", [])

    # stop if no more data
    if not results:
        break

    # Add current page results to all_stations list
    all_stations.extend(results)

    # if last page less than limit, stop
    if len(results) < params["limit"]:
        break

    #Move to next page using offset pagination
    params["offset"] += params["limit"]

# Convert all stations list to Dataframe
stations_df = pd.DataFrame(all_stations)

In [16]:
stations_df.head()

,elevation,mindate,maxdate,latitude,name,datacoverage,id,elevationUnit,longitude
0,282.5,2008-01-01,2015-06-01,35.011389,"ARDMORE 1.3 NE, TN US",0.3224,GHCND:US1CHARM185,METERS,-86.839167
1,270.1,2007-05-01,2026-06-01,36.019079,"OAK RIDGE 5.7 NE, TN US",0.8869,GHCND:US1TNAN0003,METERS,-84.221136
2,360.0,2008-06-01,2009-06-01,36.008300,"OAK RIDGE 3.3 NNW, TN US",0.7706,GHCND:US1TNAN0004,METERS,-84.311200
3,274.3,2007-05-01,2008-10-01,36.031200,"CLINTON 4.3 SSW, TN US",0.6088,GHCND:US1TNAN0006,METERS,-84.150000
4,353.0,2007-10-01,2026-06-01,36.199700,"NORRIS 0.6 NW, TN US",0.9067,GHCND:US1TNAN0008,METERS,-84.076500

In [17]:
stations_df.shape

(1351, 9)

In [ ]:
# Export Raw stations Data frame to csv file
stations_df.to_csv('../data/Raw_stations_df', index=False)

# Get Monthly Weather Data

Get Api from this link https://www.ncei.noaa.gov/cdo-web/webservices/v2#data for the weather history

In [ ]:
# weather_base_url = "https://www.ncei.noaa.gov/cdo-web/api/v2/data"

# headers = {
#     "token": noaa_weather_api_key
# }

# params = {
                
#             "datasetid": "GSOM",
#             "locationid": "FIPS:47",
#             "startdate": "2010-01-01",
#             "enddate": "2017-12-31",
#             "datatypeid": "TMIN",
#             "limit": 1000
#         }
# weather_response = requests.get(weather_base_url,headers=headers, params=params)
# weather = weather_response.json()
# weather.keys()
# weather_response

In [ ]:
#weather_response.text

In [ ]:
# weather_repo = weather['results']
# pd.DataFrame(weather_repo)

### Download monthly weather data (PRCP, TMAX, TMIN) for every station
###### Download monthly precipitation, maximum temperature, and minimum temperature.
###### The weather records contain a station ID, but they do not contain county names.

In [20]:
# Base URL for NCEI NOAA WEATHER API 

weather_base_url = 'https://www.ncei.noaa.gov/cdo-web/api/v2/data'

headers = {
    "token": noaa_weather_api_key
}

all_weather = []

dataTypes = ['PRCP','TMAX', 'TMIN']

for dataType in dataTypes:
    
    for year in range(2000, 2025):
        offset = 1  # pagination start
        
        while True:
        # Define Query Parameters for filtering the data set  
        # Get the keys from https://www.ncei.noaa.gov/cdo-web/webservices/v2#data 
            params = {
                "datasetid": "GSOM",
                "locationid": "FIPS:47",
                "startdate": f"{year}-01-01",
                "enddate": f"{year}-12-31",
                "datatypeid": dataType,
                "units" : "standard",
                "limit": 1000,
                "offset": offset
            }
                
              # Send Get Request to ncei NOAA  API with Parameters
            weather_response = requests.get(weather_base_url, headers=headers, params=params, timeout=60)
              # Convert API Response in to Python dictonary
            weather_data = weather_response.json()
            if weather_response.status_code != 200:
                print(f"Failed: {dataType} {year}")
                break

            results = weather_data.get("results",[])

            if len(results) == 0:
                break

            all_weather.extend(results)

            if len(results) < 1000:
                break

            offset += 1000

            #weather_data.keys()
            #if "results" in weather_data:
                #all_weather.extend(weather_data["results"])
            #offset += 1000
weather_df = pd.DataFrame(all_weather)

In [ ]:
#Export Raw weather Data frame to csv file
weather_df.to_csv('../data/Raw_weather_df', index=False)

In [ ]:
weather_df.head()

In [ ]:
weather_df.shape

### Download Tennessee County Boundaries (Tiger/Line Shapefile) https://www2.census.gov/geo/tiger/TIGER2023/COUNTY/¶

##### NOAA stations only have latitude and longitude.
##### We need county boundary polygons so we can determine which county each station belongs to.

#### Load Tennessee county boundary shapefile from the US Census

In [ ]:
# Read County Zip file
counties = gpd.read_file('../data/tl_2023_us_county.zip')
counties.head()

In [ ]:
# Get only TN Counties 
tn_counties = counties[counties["STATEFP"] == "47"]

In [ ]:
tn_counties.head()

In [ ]:
# Export tn_counties to csv file
tn_counties.to_csv('../data/Raw_tn_counties_df', index=False)

In [ ]:
# Take only county name and polygons
tn_counties = tn_counties[["NAME", "geometry"]]
tn_counties = tn_counties.rename(columns={"NAME": "county"})

In [ ]:
tn_counties.head()

### Convert Pandas Stations df into geospatial df to do spatial Operations

#### Convert station latitude and longitude into geographic points
##### GeoPandas spatial joins work with geographic objects.
##### This converts station coordinates into map points.

In [ ]:
#Convert pandas stations df to geospatial df
stations_gdf = gpd.GeoDataFrame(
    stations_df,
    #Create Geometry Column using longitude and latitude
    geometry=gpd.points_from_xy(stations_df.longitude, stations_df.latitude),
    # Create Coordinate system of input coordinates
    crs="EPSG:4326"
)

In [ ]:
stations_gdf.head()

#### Match Coordinate Reference System
##### Spatial joins only work correctly when both datasets use the same coordinate system.

In [ ]:
# Change the coordinate system of stations to match with count shape files data (if needed)
stations_gdf = stations_gdf.to_crs(tn_counties.crs)

In [ ]:
print(stations_gdf.crs)
print(tn_counties.crs)

#### Spatial Joins
##### Assign each Weather station to its corresponding County

In [ ]:
# Join Weather Stations to Counties
stations_county = gpd.sjoin(
    stations_gdf,
    tn_counties,
    how="left",
    predicate="within" #Match if station lies inside county boundary
)

In [ ]:
stations_county[stations_county["county"].isna()]

#### Handle Stations outside County boundaries
##### Assign nearby stations to the nearest county
##### Some stations fall just outside county boundaries.
##### Instead of losing those stations, assign them to the nearest county.

In [ ]:
# Find the nearest county based on coordinates by using sjoin_nearest for missed county
inside_stations = stations_county.copy()

In [ ]:

missing = inside_stations[inside_stations["county"].isna()]

In [ ]:
# join tn_counties and missing data
nearest = gpd.sjoin_nearest(
    #Remove geopandas join helper column, do not need it
    missing.drop(columns=["index_right"]),
    tn_counties,
    how="left",
    distance_col="dist_km"
)

#### Combine All Stations
##### Combine stations inside counties and stations matched to nearest counties

In [ ]:
# Concatenate actual county stations and the rows which has neares county
stations_with_county = pd.concat(
    [inside_stations[~inside_stations["county"].isna()], nearest],
    ignore_index=True
)

In [ ]:
stations_with_county[stations_with_county["county"].isna()]

In [ ]:
stations_with_county["final_county"] = stations_with_county["county"].fillna(stations_with_county["county_right"])

In [ ]:
# Drop unnecessary extra county columns after joining
stations_with_county = stations_with_county.drop(columns=[
    "county", "county_right", "index_right"
])

In [ ]:
# Rename
stations_with_county= stations_with_county.rename(columns={"final_county": "county"})

In [ ]:
stations_with_county.info()

In [ ]:
# Check if there are any missing values of county column, if any use gpd.sjpoin_nearest assign weather station to a nearest county
stations_with_county["county"].isna().sum()

In [ ]:
#Export Raw weather Data frame to csv file
stations_with_county.to_csv('../data/stations_with_county_df', index=False)

#### Extract Year from weather dates
##### Crop yield is annual.
##### We need yearly weather summaries.
##### Convert datatypes of date column in weather df

In [ ]:
weather_df["date"] = pd.to_datetime(weather_df["date"])
weather_df["year"] = weather_df["date"].dt.year

In [ ]:
weather_df

#### Convert Weather Data from long format to wide format
##### Convert weather data into one row per station and year

In [ ]:
# Reshape weather df from long format to wide format
weather_pivot = weather_df.pivot_table(
    #Group records by station and year
    index=["station", "year"],
    # Create seperate columns for each weather datatype variable
    columns="datatype",
    values="value",
    # If multiple values take avg
    aggfunc="mean"
    #Convert grouped index back to normal columns
).reset_index()

In [ ]:
weather_pivot.head()

#### Now Merge pivoted Weather df with county information stations with county df
##### Weather data only knows the station ID.
##### The station lookup tells us which county each station belongs to.

In [ ]:
# Merge pivoted Weather df to stations with county df
weather_station_county = weather_pivot.merge(
    stations_with_county[["id", "county"]],
    left_on="station",
    right_on="id",
    how="left"
)

In [ ]:
weather_station_county

In [ ]:
weather_station_county[weather_station_county['county'].isna()]

In [ ]:
weather_station_county = weather_station_county.dropna(subset=["county"])

In [ ]:
weather_station_county[weather_station_county['county'].isna()]

In [ ]:
#Export  weather station county Data frame to csv file
weather_station_county.to_csv('../data/weather_station_county_df', index=False)

#### Aggregate Station Data to County Level
##### A county may contain multiple weather stations.
##### Crop yield is reported at the county level.
##### Average the weather measurements across all stations in that county.
##### Calculate average weather for each county and year

In [ ]:
# Aggregate Station level weather data into county year average weather features(PRCP, TMAX, TMIN)
county_weather = weather_station_county.groupby(
    ["county", "year"]
).agg({
    "PRCP": "mean",
    "TMAX": "mean",
    "TMIN": "mean"
}).reset_index()

In [ ]:
#Export  county weather Data frame to csv file
county_weather.to_csv('../data/final_county_weather_df', index=False)

In [ ]:
county_weather.shape

# Gather Soil Data

#### Down load data set from this soil Survey Geographic database https://www.nrcs.usda.gov/resources/data-and-reports/gridded-soil-survey-geographic-gssurgo-database
click on State Databases - soils | Powered by Box

In [ ]:
# Read SSURGO soil map unit polygons for Tennessee.
# Each row represents a soil unit boundary with geometry and MUKEY identifier.
soil_keys = gpd.read_file("../data/gSSURGO_TN.gdb", layer="MUPOLYGON") #MULTIPOLYGON - a single geometric object that represents a collection of multiple, non-overlapping polygons treated as one feature

In [ ]:
soil_keys.head()

In [ ]:
# Load soil attribute table (Muaggatt) from SSURGO geodatabase
# This table contains soil properties (e.g., slope, drainage, water capacity)
# Each record is identified by MUKEY, which links to soil polygon geometries
muaggatt_df =gpd.read_file("../data/gSSURGO_TN.gdb", layer="Muaggatt")

In [ ]:
muaggatt_df.head()

Merge soil spatial polygons with soil attribute table.
soil_keys contains geometry (soil map unit boundaries).
muaggatt_df contains soil properties (slope, drainage, water capacity, etc.).
We join using MUKEY (from spatial data) and mukey (from attributes table).
This attaches soil characteristics to each soil polygon.

In [ ]:
soil_gdf = soil_keys.merge(muaggatt_df,left_on="MUKEY",right_on="mukey",how="left")

In [ ]:
soil_gdf.head()

In [ ]:
soil_gdf.info()

Keep only required soil features like water availability features("aws025wta","aws050wta","aws0100wta","aws0150wta"), Drainage features(hydgrpdcd,drclassdcd,drclasswettest,hydclprs), Fllod risk ("flodfreqdcd","flodfreqmax"), Terrain(slopegraddcp,slopegradwta), Soil Depth (brockdepmin,wtdepannmin,wtdepaprjunmin)

In [ ]:
soil_gdf_prop = soil_gdf[["geometry","aws025wta","aws050wta","aws0100wta","aws0150wta","hydgrpdcd","drclassdcd","drclasswettest","slopegraddcp","slopegradwta","brockdepmin","wtdepannmin","wtdepaprjunmin"]]

In [ ]:
tn_counties

#### Convert CRS
##### Convert both datasets to an equal-area projection (EPSG:5070).
##### Accurate area calculations require an equal-area coordinate system.

In [ ]:
# Convert soil_gdf_prop and tn_counties to equal area projection(epsg=5070)
soil_gdf_prop = soil_gdf.to_crs(epsg=5070)
tn_counties = tn_counties.to_crs(epsg=5070)

#### Calculate the percentage of county for soil type
##### Intersect soil polygons with county boundaries.
##### This determines how much of each soil polygon lies inside each county.

In [ ]:
#Compute overlapping Geometries
intersections = gpd.overlay(soil_gdf_prop, tn_counties, how='intersection')

In [ ]:
intersections

#### Calculate Soil Polygon Area
##### Calculate the area of each intersected soil polygon.
##### This is used to determine the percentage of county covered by each soil type.

In [ ]:
#Area of Soil Polygon piece
intersections["soil_area"]= intersections.geometry.area

##### Calculate the total area of each county.
##### Required to compute area-weighted soil properties

In [ ]:
# Area of County polygon
county_area = tn_counties.copy()
county_area["county_area"] = county_area.geometry.area

##### Attach county area to each intersected soil polygon.
##### This allows calculation of the proportion of each soil polygon within a county.

In [ ]:
# Merge two data frames
soil_county_intersection = intersections.merge(county_area, on="county")

##### Calculate the fraction of each county occupied by each soil polygon.
##### These percentages are used as weights when aggregating soil properties.

In [ ]:
# Calculate the percentage of county for soil type
soil_county_intersection["percent"] = soil_county_intersection["soil_area"] / soil_county_intersection["county_area"]

In [ ]:
soil_county_intersection.info()

In [ ]:
soil_county_intersection.shape

##### Multiply each soil property by its area percentage.
##### Larger soil areas contribute more to the county average.

In [ ]:
#Aggregate numerical columns by using weighted mean(since it has area percentage so using weighted mean)
for col in num_cols:
    soil_county_intersection[f"{col}_weighted"] = (soil_county_intersection[col]* soil_county_intersection["percent"])

In [ ]:
 soil_county_intersection["aws025wta_weighted"]

In [ ]:
# Multiply each soil property by its area percentage.
# Larger soil areas contribute more to the county average.

In [ ]:
# Soil Numeric columns
num_cols = ["aws025wta","aws050wta","aws0100wta","aws0150wta",
            "slopegraddcp","slopegradwta",
            "brockdepmin","wtdepannmin","wtdepaprjunmin"
           ]

In [ ]:
weighted_cols = [f"{col}_weighted" for col in num_cols]
soil_num_weighted_mean = soil_county_intersection.groupby("county")[weighted_cols].sum().reset_index()

In [ ]:
#Rename weighted columns for consistency
soil_num_weighted_mean = soil_num_weighted_mean.rename(columns={
    "aws025wta_weighted": "aws025wta",
    "aws050wta_weighted": "aws050wta",
    "aws0100wta_weighted": "aws0100wta",
    "aws0150wta_weighted": "aws0150wta",
    "slopegraddcp_weighted": "slopegraddcp",
    "slopegradwta_weighted": "slopegradwta",
    "brockdepmin_weighted": "brockdepmin",
    "wtdepannmin_weighted": "wtdepannmin",
    "wtdepaprjunmin_weighted": "wtdepaprjunmin"
})

In [ ]:
soil_num_weighted_mean.head()

In [ ]:
# Calculate the percentage of each county covered by each
# categorical soil class (drainage, hydrologic group, etc.).

In [ ]:
cat_cols = ["hydgrpdcd","drclassdcd","drclasswettest"]

In [ ]:
#aggregation of categorical column
#soil_county_intersection.groupby(["county","hydgrpdcd"])["percent"].sum()

In [ ]:
#Aggregation of Categorical Columns

soil_cat_pct = []
for col in cat_cols:
    temp = soil_county_intersection.groupby(["county", col])["percent"].sum().reset_index()
    temp = temp.pivot_table(
        index="county",
        columns=col,
        values="percent",
        fill_value=0
    )

    # adding the category name in front of column names to keep them unique during merge
    temp = temp.add_prefix(f"{col}_")
    temp = temp.reset_index()
    soil_cat_pct.append(temp)

In [ ]:
#Convert soil_cat_pct list in to date frame
#convet each list into df and merge them
soil_cat_pct_df = soil_cat_pct[0]

for df in soil_cat_pct[1:]:
    soil_cat_pct_df = soil_cat_pct_df.merge(df, on="county", how="outer")

In [ ]:
soil_cat_pct_df.columns

In [ ]:
# Merge Numerical and categorical Data 
soil_prop_data = soil_num_weighted_mean.merge(
    soil_cat_pct_df,
    on="county",
    how="left"
)

In [ ]:
#Export  Soil Properties Data frame to csv file
soil_prop_data.to_csv('../data/soil_prop_data _df', index=False)

In [ ]:
soil_prop_data.head()

In [ ]:
soil_prop_data.info()

#### Soil nutrients data
##### Gather PH values of soil

#### Read Component Layer

In [ ]:
comp = gpd.read_file("../data/gSSURGO_TN.gdb", layer="component")

In [ ]:
comp.head()

In [ ]:
comp.shape

In [ ]:
comp.columns.tolist()

PH Values are not in the Copmponent Table. Check chorizon table

#### Read CHorizon Layer

In [ ]:
chorizon = gpd.read_file("../data/gSSURGO_TN.gdb", layer="chorizon")

In [ ]:
chorizon.columns.tolist()

In [ ]:
[col for col in chorizon.columns if "ph" in col.lower()]

In [ ]:
# Get only required nutrient columns
soil_nutrients = chorizon[["cokey","ph1to1h2o_r","om_r"]].copy() #make as independent dataframe

In [ ]:
soil_nutrients.head()

In [ ]:
soil_nutrients.info()

In [ ]:
# Handle missing values for soil nutrients
# Filling missing values by median beacause it will not effected by outliers and  mean gets pulled by extreme values will be affected by outliers
soil_nutrients["ph1to1h2o_r"] = soil_nutrients["ph1to1h2o_r"].fillna(soil_nutrients["ph1to1h2o_r"].median())
soil_nutrients["om_r"] = soil_nutrients["om_r"].fillna(soil_nutrients["om_r"].median())

In [ ]:
# Aggregate these nutrients to component level to remove duplicates
soil_nutrients = soil_nutrients.groupby("cokey")[["ph1to1h2o_r", "om_r"]].mean().reset_index()

In [ ]:
soil_nutrients.shape

##### Merge soil nutrients to soil county interactions to get the county level aggregation

In [ ]:
# To merge soil nutrients to soil county interactions it does not have cokey key so mergeing it with component level and then will merge it with mapunit level (mukey)

comp_nutrients = comp.merge(soil_nutrients,on="cokey",how="left")

In [ ]:
comp_nutrients.shape

In [ ]:
# Aggregate the components to mukey level
mukey_nutrients = comp_nutrients.groupby("mukey")[["ph1to1h2o_r", "om_r"]].mean().reset_index()

In [ ]:
# NOw merge into spatial county dataset
soil_county_intersection = soil_county_intersection.merge(mukey_nutrients,on="mukey",how="left")

In [ ]:
soil_county_intersection.columns.tolist()

In [ ]:
# Aggregate nutrients by weighted mean
soil_county_intersection["ph1to1h2o_r_weighted"] = soil_county_intersection["ph1to1h2o_r"]* soil_county_intersection["percent"]
soil_ph = soil_county_intersection.groupby("county")["ph1to1h2o_r_weighted"].sum().reset_index()

soil_county_intersection["om_r_weighted"] = soil_county_intersection["om_r"]* soil_county_intersection["percent"]
soil_om = soil_county_intersection.groupby("county")["om_r_weighted"].sum().reset_index()

soil_nutrients = soil_ph.merge(soil_om, on='county')

In [ ]:
soil_nutrients

In [ ]:
#Export soil nutrients data to csv file
soil_nutrients.to_csv('../data/soil_nutrients_df', index=False)

In [ ]:
# Merge soil properties and soil nutrients datasets
final_soil_data = soil_prop_data.merge(soil_nutrients,on="county",how="left")

In [ ]:
final_soil_data

In [ ]:
final_soil_data.columns.tolist

In [ ]:
#Export Export final soil data to csv file
final_soil_data.to_csv('../data/final_soil_data', index=False)